### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by ndenggg** [ENAleksey/RenderEdge_Widescreen#1]
First thank you for developing this tool - I have been playing war3 since many years ago, it's great to play it in a wide screen ^_^

I just want to test it on my local PC, by any chance you can share how do you compile this project and generate the .mix file? I tried to use msbuild but saw error:
Cannot open include file: "windows.h": No such file or dir

After tried to Google I found I may miss the Windows SDK - however, after checking Win10 SDK in installer I still see the same error. What did miss? Can you share some thoughts?

**Comment by ENAleksey** [comment]
Hi!
You can build the project with Visual Studio.
Or just download .mix file from here: https://github.com/ENAleksey/RenderEdge_Widescreen/releases/tag/v1.2.0c
