### ISSUE TITLE
Prevent UI Stretch

### ISSUE THREAD

**Issue by erfanmola** [ENAleksey/RenderEdge_Widescreen#2]
Hi, first of all, I want to say a big thanks ! Thanks man, this is awesome, you did a great job with this project, eventually u made 1.31 and up resoloution available in low versions and thats epic

The only thing that is  still not as good, is UI, I saw your work about memory hack and I'm sure you are a pro with UI stuff too, so thats why I'm asking if it is possible, fix UI stretch

[Here is a demo of 1.31 and reforged](https://static2.thegamerimages.com/wordpress/wp-content/uploads/2020/02/Reforged-UI-comparison-1.jpg), both are nice, it would be really good if we get option to choose between UI mode, transparent or full, or anything but not the default stretch ! stretching makes it really ugly, the square boxes become rectangle and the map preview gets oversize and so on ...

And again, a Huge thanks for this epic project

**Comment by ENAleksey** [comment]
Hi!

I have already tried to fix the interface, with some successes. For example, these are imported interface textures from the mod for Starcraft - Armies of Azeroth:

![image](https://user-images.githubusercontent.com/12061580/114171989-80a92680-994e-11eb-8a5a-c321fabfadf8.png)

And this is the standard Warcraft interface:

![image](https://user-images.githubusercontent.com/12061580/114172790-9408c180-994f-11eb-96ea-f494e7bc5c3b.png)
![image](https://user-images.githubusercontent.com/12061580/114172804-9a973900-994f-11eb-9fa9-ceef8cdf9ee8.png)

But I never managed to merge and move all parts of the interface to the center.

And now I don't have enough time to do things with Warcraft due work and study, but maybe someday I'll try to do something else.

**Comment by erfanmola** [comment]
Thanks for response, how can i alter mine to these UI's, any link or description ?
I do really appreciate your works, I'm looking forward when you get free time, work on a non-stretching ui in center, it would be epic
And again, Thanks for this epic widescreen fix, It really makes 1.26 and ... look like 1.31

and one more thing, Im also a developer and interested in tweakings like this, But i have no familiarity with writing mods for W3, Is there any source to learn about writing .mix mods for W3  with cpp or ... ?

**Comment by ENAleksey** [comment]
Unfortunately, there are no working versions with this interface. I was just experimenting: intercepting functions from game.dll and replacing them with my own, replacing parameters in them or doing my own calculations. After I realized that further manipulation with them would not give anything better, I deleted them and looked for other functions in game.dll.

To load your .dll into Warcraft, nothing special is required, you just need to change the extension to .mix and place file in Warcraft folder. The library will be loaded automatically on war3.exe started, but after game.dll loaded, and execute its code located in [entry point](https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain) function. Then you can do whatever you want.

The main source code of Warcraft is placed in game.dll. You can see it using something like [IDA Pro](https://www.hex-rays.com/products/ida/).
BTW, you can download my [.idb file of game.dll](https://1drv.ms/u/s!AqVSeI6Ewf_zj15SWYOEDqaM_Lb1?e=mA5d7f) for Warcraft patch 1.26a. I already found many functions and named them (also for UI rendering):

![image](https://user-images.githubusercontent.com/12061580/114925836-09412e80-9e49-11eb-8a11-3d5291b7e32d.png)

You can intercept functions and replace their functionality by [Microsoft Detours](https://github.com/microsoft/Detours).
You can also call any function from game.dll, just define it like it defined in .dll and specify function address: https://github.com/ENAleksey/RenderEdge_Widescreen/blob/17b82df5522ae3b7f330038bb57ff8a3f0809ed2/RenderEdge_Widescreen/DllMain.cpp#L54

**Comment by mosishon** [comment]
**thanks a lot.** Your work is truly **admirable**. Thank you very much if you fix the **UI problem**

**Comment by erfanmola** [comment]
looking forward to it

**Comment by erfanmola** [comment]
Cant we just replace the code from 1.28+ with the 1.26a ?
Also another thing that bothers is fps, Cant we remove 60fps limit in lower versions ? it seems to be fixed to 60fps
even by editing the registery values

It would be epic if you put time on reviving old patches, Battle.net guys are ok, but GameRanger guys and other client player still use 1.26a and we still use the performance of 20 years ago

**Comment by ENAleksey** [comment]
I have already removed the FPS limit for patch 1.26a:
https://github.com/ENAleksey/RenderEdge/blob/7e2d614163fd22680da6d21444f8daf032749894/RenderEdge/Source/DllMain.cpp#L185
You can also turn off VSync so the fps can rise above the refresh rate of monitor.

Game with and without VSync (local game, removed fps limit):
![image](https://user-images.githubusercontent.com/12061580/117792991-3b398b00-b265-11eb-9515-38e4fb0004cc.png)
![image](https://user-images.githubusercontent.com/12061580/117793003-3ffe3f00-b265-11eb-8bff-c30ef059dcfc.png)

It's easy to find addresses for other patches, but I removed all my game.dll and .idb files except for 1.26a.
Patches 1.28+ now has protection against decompilation, it became very difficult to do, so I decided not to work with them.

**Comment by erfanmola** [comment]
Thanks for response,
Warcraft 1.26 does not have an option to disable VSync
I could disable VSync from options in 1.31, but no such an option in 1.26a, I think you should add the code to disable it in renderedge_widescreen

I also could not disable VSync globally in my Laptop since it uses Intel Graphics of CPU for W3, not my GPU
and Intel Graphics in my pc has no advanced options for switching VSync

Another possiblity would be -nativefullscr that is missing in 1.26a, that might be the key to turned off VSync in W3, but not available in 1.26a

I also tried launching W3 with renderedge in-order to turn off vsync with it, but it says failed to load RenderEdge.dll
I would be thankful if you guide how to disable VSync manually, or with a .mix file

**Comment by maryamshm** [comment]
Hi, we would be grateful if you consider fixing UI Stretch and also disabling VSync by default on lower patches, since we still use them and we want to get the nowadays experience from them

**Comment by erfanmola** [comment]
It would be very nice if you consider disabling VSync in this project, since most people play W3 on GameRanger or etc, and the dont launch it using RenderEdge, the Game Client launches W3 itself

**Comment by mazyardosti** [comment]
Hi It would be nice if you disable VSync by default and also have a plan to fix UI Stretch based on newer patches in later versions
